// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: api/howl/v1/canidae.proto

package howlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamEventType int32

const (
	StreamEventType_STREAM_EVENT_TYPE_UNSPECIFIED StreamEventType = 0
	StreamEventType_STREAM_EVENT_TYPE_DATA        StreamEventType = 1
	StreamEventType_STREAM_EVENT_TYPE_ERROR       StreamEventType = 2
	StreamEventType_STREAM_EVENT_TYPE_COMPLETE    StreamEventType = 3
	StreamEventType_STREAM_EVENT_TYPE_HEARTBEAT   StreamEventType = 4
	StreamEventType_STREAM_EVENT_TYPE_PROGRESS    StreamEventType = 5
)

// Enum value maps for StreamEventType.
var (
	StreamEventType_name = map[int32]string{
		0: "STREAM_EVENT_TYPE_UNSPECIFIED",
		1: "STREAM_EVENT_TYPE_DATA",
		2: "STREAM_EVENT_TYPE_ERROR",
		3: "STREAM_EVENT_TYPE_COMPLETE",
		4: "STREAM_EVENT_TYPE_HEARTBEAT",
		5: "STREAM_EVENT_TYPE_PROGRESS",
	}
	StreamEventType_value = map[string]int32{
		"STREAM_EVENT_TYPE_UNSPECIFIED": 0,
		"STREAM_EVENT_TYPE_DATA":        1,
		"STREAM_EVENT_TYPE_ERROR":       2,
		"STREAM_EVENT_TYPE_COMPLETE":    3,
		"STREAM_EVENT_TYPE_HEARTBEAT":   4,
		"STREAM_EVENT_TYPE_PROGRESS":    5,
	}
)

func (x StreamEventType) Enum() *StreamEventType {
	p := new(StreamEventType)
	*p = x
	return p
}

func (x StreamEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_howl_v1_canidae_proto_enumTypes[0].Descriptor()
}

func (StreamEventType) Type() protoreflect.EnumType {
	return &file_api_howl_v1_canidae_proto_enumTypes[0]
}

func (x StreamEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamEventType.Descriptor instead.
func (StreamEventType) EnumDescriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{0}
}

// Request is a generic request wrapper
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	PackId        string                 `protobuf:"bytes,3,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Request) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

func (x *Request) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Request) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Response is a generic response wrapper
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Response) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Response) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Error represents an error response
type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// StreamMessage for bidirectional streaming
type StreamMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          StreamEventType        `protobuf:"varint,2,opt,name=type,proto3,enum=howl.v1.StreamEventType" json:"type,omitempty"`
	Data          *anypb.Any             `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMessage) Reset() {
	*x = StreamMessage{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessage) ProtoMessage() {}

func (x *StreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessage.ProtoReflect.Descriptor instead.
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{3}
}

func (x *StreamMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamMessage) GetType() StreamEventType {
	if x != nil {
		return x.Type
	}
	return StreamEventType_STREAM_EVENT_TYPE_UNSPECIFIED
}

func (x *StreamMessage) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamMessage) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *StreamMessage) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StreamMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// ExecuteRequest for single agent execution
type ExecuteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentType       string                 `protobuf:"bytes,1,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Prompt          string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model           string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Temperature     float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens       int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	SecurityProfile *SecurityProfile       `protobuf:"bytes,6,opt,name=security_profile,json=securityProfile,proto3" json:"security_profile,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *ExecuteRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ExecuteRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExecuteRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ExecuteRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ExecuteRequest) GetSecurityProfile() *SecurityProfile {
	if x != nil {
		return x.SecurityProfile
	}
	return nil
}

func (x *ExecuteRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ExecuteResponse from single agent
type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,3,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecuteResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *ExecuteResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *ExecuteResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ExecuteResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ExecuteResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ChainRequest for sequential agent execution
type ChainRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Steps           []*ChainStep           `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	SecurityProfile *SecurityProfile       `protobuf:"bytes,2,opt,name=security_profile,json=securityProfile,proto3" json:"security_profile,omitempty"`
	ContinueOnError bool                   `protobuf:"varint,3,opt,name=continue_on_error,json=continueOnError,proto3" json:"continue_on_error,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChainRequest) Reset() {
	*x = ChainRequest{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainRequest) ProtoMessage() {}

func (x *ChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainRequest.ProtoReflect.Descriptor instead.
func (*ChainRequest) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{6}
}

func (x *ChainRequest) GetSteps() []*ChainStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ChainRequest) GetSecurityProfile() *SecurityProfile {
	if x != nil {
		return x.SecurityProfile
	}
	return nil
}

func (x *ChainRequest) GetContinueOnError() bool {
	if x != nil {
		return x.ContinueOnError
	}
	return false
}

func (x *ChainRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ChainStep in a chain
type ChainStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentType     string                 `protobuf:"bytes,1,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Prompt        string                 `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Temperature   float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,5,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	DependsOn     []string               `protobuf:"bytes,6,rep,name=depends_on,json=dependsOn,proto3" json:"depends_on,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainStep) Reset() {
	*x = ChainStep{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainStep) ProtoMessage() {}

func (x *ChainStep) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainStep.ProtoReflect.Descriptor instead.
func (*ChainStep) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{7}
}

func (x *ChainStep) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *ChainStep) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ChainStep) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChainStep) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChainStep) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChainStep) GetDependsOn() []string {
	if x != nil {
		return x.DependsOn
	}
	return nil
}

func (x *ChainStep) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ChainResponse from chain execution
type ChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Steps         []*StepResponse        `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainResponse) Reset() {
	*x = ChainResponse{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainResponse) ProtoMessage() {}

func (x *ChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainResponse.ProtoReflect.Descriptor instead.
func (*ChainResponse) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{8}
}

func (x *ChainResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChainResponse) GetSteps() []*StepResponse {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ChainResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *ChainResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ChainResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// StepResponse for individual chain step
type StepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepId        string                 `protobuf:"bytes,1,opt,name=step_id,json=stepId,proto3" json:"step_id,omitempty"`
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,4,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepResponse) Reset() {
	*x = StepResponse{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepResponse) ProtoMessage() {}

func (x *StepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepResponse.ProtoReflect.Descriptor instead.
func (*StepResponse) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{9}
}

func (x *StepResponse) GetStepId() string {
	if x != nil {
		return x.StepId
	}
	return ""
}

func (x *StepResponse) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *StepResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *StepResponse) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *StepResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *StepResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StepResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PackFormationRequest for pack operations
type PackFormationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Formation       *PackFormation         `protobuf:"bytes,1,opt,name=formation,proto3" json:"formation,omitempty"`
	Objective       string                 `protobuf:"bytes,2,opt,name=objective,proto3" json:"objective,omitempty"`
	SecurityProfile *SecurityProfile       `protobuf:"bytes,3,opt,name=security_profile,json=securityProfile,proto3" json:"security_profile,omitempty"`
	MaxConcurrency  int32                  `protobuf:"varint,4,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	TimeoutMs       int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PackFormationRequest) Reset() {
	*x = PackFormationRequest{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackFormationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackFormationRequest) ProtoMessage() {}

func (x *PackFormationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackFormationRequest.ProtoReflect.Descriptor instead.
func (*PackFormationRequest) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{10}
}

func (x *PackFormationRequest) GetFormation() *PackFormation {
	if x != nil {
		return x.Formation
	}
	return nil
}

func (x *PackFormationRequest) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

func (x *PackFormationRequest) GetSecurityProfile() *SecurityProfile {
	if x != nil {
		return x.SecurityProfile
	}
	return nil
}

func (x *PackFormationRequest) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *PackFormationRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *PackFormationRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PackFormation structure
type PackFormation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alpha         *PackMemberSpec        `protobuf:"bytes,1,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Hunters       []*PackMemberSpec      `protobuf:"bytes,2,rep,name=hunters,proto3" json:"hunters,omitempty"`
	Scouts        []*PackMemberSpec      `protobuf:"bytes,3,rep,name=scouts,proto3" json:"scouts,omitempty"`
	Sentries      []*PackMemberSpec      `protobuf:"bytes,4,rep,name=sentries,proto3" json:"sentries,omitempty"`
	Elders        []*PackMemberSpec      `protobuf:"bytes,5,rep,name=elders,proto3" json:"elders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackFormation) Reset() {
	*x = PackFormation{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackFormation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackFormation) ProtoMessage() {}

func (x *PackFormation) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackFormation.ProtoReflect.Descriptor instead.
func (*PackFormation) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{11}
}

func (x *PackFormation) GetAlpha() *PackMemberSpec {
	if x != nil {
		return x.Alpha
	}
	return nil
}

func (x *PackFormation) GetHunters() []*PackMemberSpec {
	if x != nil {
		return x.Hunters
	}
	return nil
}

func (x *PackFormation) GetScouts() []*PackMemberSpec {
	if x != nil {
		return x.Scouts
	}
	return nil
}

func (x *PackFormation) GetSentries() []*PackMemberSpec {
	if x != nil {
		return x.Sentries
	}
	return nil
}

func (x *PackFormation) GetElders() []*PackMemberSpec {
	if x != nil {
		return x.Elders
	}
	return nil
}

// PackMemberSpec for pack member configuration
type PackMemberSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Objective     string                 `protobuf:"bytes,3,opt,name=objective,proto3" json:"objective,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Temperature   float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,6,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackMemberSpec) Reset() {
	*x = PackMemberSpec{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackMemberSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackMemberSpec) ProtoMessage() {}

func (x *PackMemberSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackMemberSpec.ProtoReflect.Descriptor instead.
func (*PackMemberSpec) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{12}
}

func (x *PackMemberSpec) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PackMemberSpec) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *PackMemberSpec) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

func (x *PackMemberSpec) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PackMemberSpec) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *PackMemberSpec) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *PackMemberSpec) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PackFormationResponse from pack execution
type PackFormationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PackId        string                 `protobuf:"bytes,2,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
	Results       []*PackResult          `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,4,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackFormationResponse) Reset() {
	*x = PackFormationResponse{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackFormationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackFormationResponse) ProtoMessage() {}

func (x *PackFormationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackFormationResponse.ProtoReflect.Descriptor instead.
func (*PackFormationResponse) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{13}
}

func (x *PackFormationResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PackFormationResponse) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

func (x *PackFormationResponse) GetResults() []*PackResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *PackFormationResponse) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *PackFormationResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *PackFormationResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// PackResult from individual pack member
type PackResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	AgentType     string                 `protobuf:"bytes,3,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	Response      string                 `protobuf:"bytes,4,opt,name=response,proto3" json:"response,omitempty"`
	TokensUsed    int32                  `protobuf:"varint,5,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackResult) Reset() {
	*x = PackResult{}
	mi := &file_api_howl_v1_canidae_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackResult) ProtoMessage() {}

func (x *PackResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_canidae_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackResult.ProtoReflect.Descriptor instead.
func (*PackResult) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_canidae_proto_rawDescGZIP(), []int{14}
}

func (x *PackResult) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *PackResult) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PackResult) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *PackResult) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *PackResult) GetTokensUsed() int32 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *PackResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *PackResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PackResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_howl_v1_canidae_proto protoreflect.FileDescriptor

const file_api_howl_v1_canidae_proto_rawDesc = "" +
	"\n" +
	"\x19api/howl/v1/canidae.proto\x12\ahowl.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\x1a\x16api/howl/v1/howl.proto\"\x9e\x03\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\apack_id\x18\x03 \x01(\tR\x06packId\x12.\n" +
	"\apayload\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\apayload\x127\n" +
	"\aheaders\x18\x05 \x03(\v2\x1d.howl.v1.Request.HeadersEntryR\aheaders\x12:\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1e.howl.v1.Request.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x03\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12$\n" +
	"\x05error\x18\x04 \x01(\v2\x0e.howl.v1.ErrorR\x05error\x128\n" +
	"\aheaders\x18\x05 \x03(\v2\x1e.howl.v1.Response.HeadersEntryR\aheaders\x12;\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1f.howl.v1.Response.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\xd6\x02\n" +
	"\rStreamMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.howl.v1.StreamEventTypeR\x04type\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04data\x12$\n" +
	"\x05error\x18\x04 \x01(\v2\x0e.howl.v1.ErrorR\x05error\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.howl.v1.StreamMessage.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x02\n" +
	"\x0eExecuteRequest\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x01 \x01(\tR\tagentType\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12C\n" +
	"\x10security_profile\x18\x06 \x01(\v2\x18.howl.v1.SecurityProfileR\x0fsecurityProfile\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.howl.v1.ExecuteRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa5\x02\n" +
	"\x0fExecuteResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x1f\n" +
	"\vtokens_used\x18\x03 \x01(\x05R\n" +
	"tokensUsed\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12B\n" +
	"\bmetadata\x18\x06 \x03(\v2&.howl.v1.ExecuteResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x02\n" +
	"\fChainRequest\x12(\n" +
	"\x05steps\x18\x01 \x03(\v2\x12.howl.v1.ChainStepR\x05steps\x12C\n" +
	"\x10security_profile\x18\x02 \x01(\v2\x18.howl.v1.SecurityProfileR\x0fsecurityProfile\x12*\n" +
	"\x11continue_on_error\x18\x03 \x01(\bR\x0fcontinueOnError\x12?\n" +
	"\bmetadata\x18\x04 \x03(\v2#.howl.v1.ChainRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x02\n" +
	"\tChainStep\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x01 \x01(\tR\tagentType\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x05 \x01(\x05R\tmaxTokens\x12\x1d\n" +
	"\n" +
	"depends_on\x18\x06 \x03(\tR\tdependsOn\x12<\n" +
	"\bmetadata\x18\a \x03(\v2 .howl.v1.ChainStep.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9e\x02\n" +
	"\rChainResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12+\n" +
	"\x05steps\x18\x02 \x03(\v2\x15.howl.v1.StepResponseR\x05steps\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.howl.v1.ChainResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x02\n" +
	"\fStepResponse\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\x12\x1f\n" +
	"\vtokens_used\x18\x04 \x01(\x05R\n" +
	"tokensUsed\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12?\n" +
	"\bmetadata\x18\a \x03(\v2#.howl.v1.StepResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfd\x02\n" +
	"\x14PackFormationRequest\x124\n" +
	"\tformation\x18\x01 \x01(\v2\x16.howl.v1.PackFormationR\tformation\x12\x1c\n" +
	"\tobjective\x18\x02 \x01(\tR\tobjective\x12C\n" +
	"\x10security_profile\x18\x03 \x01(\v2\x18.howl.v1.SecurityProfileR\x0fsecurityProfile\x12'\n" +
	"\x0fmax_concurrency\x18\x04 \x01(\x05R\x0emaxConcurrency\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.howl.v1.PackFormationRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x02\n" +
	"\rPackFormation\x12-\n" +
	"\x05alpha\x18\x01 \x01(\v2\x17.howl.v1.PackMemberSpecR\x05alpha\x121\n" +
	"\ahunters\x18\x02 \x03(\v2\x17.howl.v1.PackMemberSpecR\ahunters\x12/\n" +
	"\x06scouts\x18\x03 \x03(\v2\x17.howl.v1.PackMemberSpecR\x06scouts\x123\n" +
	"\bsentries\x18\x04 \x03(\v2\x17.howl.v1.PackMemberSpecR\bsentries\x12/\n" +
	"\x06elders\x18\x05 \x03(\v2\x17.howl.v1.PackMemberSpecR\x06elders\"\xb8\x02\n" +
	"\x0ePackMemberSpec\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12\x1c\n" +
	"\tobjective\x18\x03 \x01(\tR\tobjective\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x06 \x01(\x05R\tmaxTokens\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.howl.v1.PackMemberSpec.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x02\n" +
	"\x15PackFormationResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\apack_id\x18\x02 \x01(\tR\x06packId\x12-\n" +
	"\aresults\x18\x03 \x03(\v2\x13.howl.v1.PackResultR\aresults\x12!\n" +
	"\ftotal_tokens\x18\x04 \x01(\x05R\vtotalTokens\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.howl.v1.PackFormationResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x02\n" +
	"\n" +
	"PackResult\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x03 \x01(\tR\tagentType\x12\x1a\n" +
	"\bresponse\x18\x04 \x01(\tR\bresponse\x12\x1f\n" +
	"\vtokens_used\x18\x05 \x01(\x05R\n" +
	"tokensUsed\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12=\n" +
	"\bmetadata\x18\b \x03(\v2!.howl.v1.PackResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xce\x01\n" +
	"\x0fStreamEventType\x12!\n" +
	"\x1dSTREAM_EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16STREAM_EVENT_TYPE_DATA\x10\x01\x12\x1b\n" +
	"\x17STREAM_EVENT_TYPE_ERROR\x10\x02\x12\x1e\n" +
	"\x1aSTREAM_EVENT_TYPE_COMPLETE\x10\x03\x12\x1f\n" +
	"\x1bSTREAM_EVENT_TYPE_HEARTBEAT\x10\x04\x12\x1e\n" +
	"\x1aSTREAM_EVENT_TYPE_PROGRESS\x10\x052\xdf\x01\n" +
	"\x0eCanidaeService\x12.\n" +
	"\aExecute\x12\x10.howl.v1.Request\x1a\x11.howl.v1.Response\x12,\n" +
	"\x05Chain\x12\x10.howl.v1.Request\x1a\x11.howl.v1.Response\x121\n" +
	"\n" +
	"SummonPack\x12\x10.howl.v1.Request\x1a\x11.howl.v1.Response\x12<\n" +
	"\x06Stream\x12\x16.howl.v1.StreamMessage\x1a\x16.howl.v1.StreamMessage(\x010\x01B1Z/github.com/macawi-ai/canidae/api/howl/v1;howlv1b\x06proto3"

var (
	file_api_howl_v1_canidae_proto_rawDescOnce sync.Once
	file_api_howl_v1_canidae_proto_rawDescData []byte
)

func file_api_howl_v1_canidae_proto_rawDescGZIP() []byte {
	file_api_howl_v1_canidae_proto_rawDescOnce.Do(func() {
		file_api_howl_v1_canidae_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_howl_v1_canidae_proto_rawDesc), len(file_api_howl_v1_canidae_proto_rawDesc)))
	})
	return file_api_howl_v1_canidae_proto_rawDescData
}

var file_api_howl_v1_canidae_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_howl_v1_canidae_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_api_howl_v1_canidae_proto_goTypes = []any{
	(StreamEventType)(0),          // 0: howl.v1.StreamEventType
	(*Request)(nil),               // 1: howl.v1.Request
	(*Response)(nil),              // 2: howl.v1.Response
	(*Error)(nil),                 // 3: howl.v1.Error
	(*StreamMessage)(nil),         // 4: howl.v1.StreamMessage
	(*ExecuteRequest)(nil),        // 5: howl.v1.ExecuteRequest
	(*ExecuteResponse)(nil),       // 6: howl.v1.ExecuteResponse
	(*ChainRequest)(nil),          // 7: howl.v1.ChainRequest
	(*ChainStep)(nil),             // 8: howl.v1.ChainStep
	(*ChainResponse)(nil),         // 9: howl.v1.ChainResponse
	(*StepResponse)(nil),          // 10: howl.v1.StepResponse
	(*PackFormationRequest)(nil),  // 11: howl.v1.PackFormationRequest
	(*PackFormation)(nil),         // 12: howl.v1.PackFormation
	(*PackMemberSpec)(nil),        // 13: howl.v1.PackMemberSpec
	(*PackFormationResponse)(nil), // 14: howl.v1.PackFormationResponse
	(*PackResult)(nil),            // 15: howl.v1.PackResult
	nil,                           // 16: howl.v1.Request.HeadersEntry
	nil,                           // 17: howl.v1.Request.MetadataEntry
	nil,                           // 18: howl.v1.Response.HeadersEntry
	nil,                           // 19: howl.v1.Response.MetadataEntry
	nil,                           // 20: howl.v1.StreamMessage.MetadataEntry
	nil,                           // 21: howl.v1.ExecuteRequest.MetadataEntry
	nil,                           // 22: howl.v1.ExecuteResponse.MetadataEntry
	nil,                           // 23: howl.v1.ChainRequest.MetadataEntry
	nil,                           // 24: howl.v1.ChainStep.MetadataEntry
	nil,                           // 25: howl.v1.ChainResponse.MetadataEntry
	nil,                           // 26: howl.v1.StepResponse.MetadataEntry
	nil,                           // 27: howl.v1.PackFormationRequest.MetadataEntry
	nil,                           // 28: howl.v1.PackMemberSpec.MetadataEntry
	nil,                           // 29: howl.v1.PackFormationResponse.MetadataEntry
	nil,                           // 30: howl.v1.PackResult.MetadataEntry
	(*anypb.Any)(nil),             // 31: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 32: google.protobuf.Timestamp
	(*SecurityProfile)(nil),       // 33: howl.v1.SecurityProfile
}
var file_api_howl_v1_canidae_proto_depIdxs = []int32{
	31, // 0: howl.v1.Request.payload:type_name -> google.protobuf.Any
	16, // 1: howl.v1.Request.headers:type_name -> howl.v1.Request.HeadersEntry
	17, // 2: howl.v1.Request.metadata:type_name -> howl.v1.Request.MetadataEntry
	32, // 3: howl.v1.Request.timestamp:type_name -> google.protobuf.Timestamp
	31, // 4: howl.v1.Response.data:type_name -> google.protobuf.Any
	3,  // 5: howl.v1.Response.error:type_name -> howl.v1.Error
	18, // 6: howl.v1.Response.headers:type_name -> howl.v1.Response.HeadersEntry
	19, // 7: howl.v1.Response.metadata:type_name -> howl.v1.Response.MetadataEntry
	32, // 8: howl.v1.Response.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 9: howl.v1.StreamMessage.type:type_name -> howl.v1.StreamEventType
	31, // 10: howl.v1.StreamMessage.data:type_name -> google.protobuf.Any
	3,  // 11: howl.v1.StreamMessage.error:type_name -> howl.v1.Error
	20, // 12: howl.v1.StreamMessage.metadata:type_name -> howl.v1.StreamMessage.MetadataEntry
	32, // 13: howl.v1.StreamMessage.timestamp:type_name -> google.protobuf.Timestamp
	33, // 14: howl.v1.ExecuteRequest.security_profile:type_name -> howl.v1.SecurityProfile
	21, // 15: howl.v1.ExecuteRequest.metadata:type_name -> howl.v1.ExecuteRequest.MetadataEntry
	22, // 16: howl.v1.ExecuteResponse.metadata:type_name -> howl.v1.ExecuteResponse.MetadataEntry
	8,  // 17: howl.v1.ChainRequest.steps:type_name -> howl.v1.ChainStep
	33, // 18: howl.v1.ChainRequest.security_profile:type_name -> howl.v1.SecurityProfile
	23, // 19: howl.v1.ChainRequest.metadata:type_name -> howl.v1.ChainRequest.MetadataEntry
	24, // 20: howl.v1.ChainStep.metadata:type_name -> howl.v1.ChainStep.MetadataEntry
	10, // 21: howl.v1.ChainResponse.steps:type_name -> howl.v1.StepResponse
	25, // 22: howl.v1.ChainResponse.metadata:type_name -> howl.v1.ChainResponse.MetadataEntry
	26, // 23: howl.v1.StepResponse.metadata:type_name -> howl.v1.StepResponse.MetadataEntry
	12, // 24: howl.v1.PackFormationRequest.formation:type_name -> howl.v1.PackFormation
	33, // 25: howl.v1.PackFormationRequest.security_profile:type_name -> howl.v1.SecurityProfile
	27, // 26: howl.v1.PackFormationRequest.metadata:type_name -> howl.v1.PackFormationRequest.MetadataEntry
	13, // 27: howl.v1.PackFormation.alpha:type_name -> howl.v1.PackMemberSpec
	13, // 28: howl.v1.PackFormation.hunters:type_name -> howl.v1.PackMemberSpec
	13, // 29: howl.v1.PackFormation.scouts:type_name -> howl.v1.PackMemberSpec
	13, // 30: howl.v1.PackFormation.sentries:type_name -> howl.v1.PackMemberSpec
	13, // 31: howl.v1.PackFormation.elders:type_name -> howl.v1.PackMemberSpec
	28, // 32: howl.v1.PackMemberSpec.metadata:type_name -> howl.v1.PackMemberSpec.MetadataEntry
	15, // 33: howl.v1.PackFormationResponse.results:type_name -> howl.v1.PackResult
	29, // 34: howl.v1.PackFormationResponse.metadata:type_name -> howl.v1.PackFormationResponse.MetadataEntry
	30, // 35: howl.v1.PackResult.metadata:type_name -> howl.v1.PackResult.MetadataEntry
	1,  // 36: howl.v1.CanidaeService.Execute:input_type -> howl.v1.Request
	1,  // 37: howl.v1.CanidaeService.Chain:input_type -> howl.v1.Request
	1,  // 38: howl.v1.CanidaeService.SummonPack:input_type -> howl.v1.Request
	4,  // 39: howl.v1.CanidaeService.Stream:input_type -> howl.v1.StreamMessage
	2,  // 40: howl.v1.CanidaeService.Execute:output_type -> howl.v1.Response
	2,  // 41: howl.v1.CanidaeService.Chain:output_type -> howl.v1.Response
	2,  // 42: howl.v1.CanidaeService.SummonPack:output_type -> howl.v1.Response
	4,  // 43: howl.v1.CanidaeService.Stream:output_type -> howl.v1.StreamMessage
	40, // [40:44] is the sub-list for method output_type
	36, // [36:40] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_api_howl_v1_canidae_proto_init() }
func file_api_howl_v1_canidae_proto_init() {
	if File_api_howl_v1_canidae_proto != nil {
		return
	}
	file_api_howl_v1_howl_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_howl_v1_canidae_proto_rawDesc), len(file_api_howl_v1_canidae_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_howl_v1_canidae_proto_goTypes,
		DependencyIndexes: file_api_howl_v1_canidae_proto_depIdxs,
		EnumInfos:         file_api_howl_v1_canidae_proto_enumTypes,
		MessageInfos:      file_api_howl_v1_canidae_proto_msgTypes,
	}.Build()
	File_api_howl_v1_canidae_proto = out.File
	file_api_howl_v1_canidae_proto_goTypes = nil
	file_api_howl_v1_canidae_proto_depIdxs = nil
}
