// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: api/howl/v1/howl.proto

package howlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackRole int32

const (
	PackRole_PACK_ROLE_UNSPECIFIED PackRole = 0
	PackRole_PACK_ROLE_ALPHA       PackRole = 1 // Coordinator
	PackRole_PACK_ROLE_HUNTER      PackRole = 2 // Task executor
	PackRole_PACK_ROLE_SCOUT       PackRole = 3 // Explorer
	PackRole_PACK_ROLE_SENTRY      PackRole = 4 // Security
	PackRole_PACK_ROLE_ELDER       PackRole = 5 // Knowledge
	PackRole_PACK_ROLE_PUP         PackRole = 6 // Training
)

// Enum value maps for PackRole.
var (
	PackRole_name = map[int32]string{
		0: "PACK_ROLE_UNSPECIFIED",
		1: "PACK_ROLE_ALPHA",
		2: "PACK_ROLE_HUNTER",
		3: "PACK_ROLE_SCOUT",
		4: "PACK_ROLE_SENTRY",
		5: "PACK_ROLE_ELDER",
		6: "PACK_ROLE_PUP",
	}
	PackRole_value = map[string]int32{
		"PACK_ROLE_UNSPECIFIED": 0,
		"PACK_ROLE_ALPHA":       1,
		"PACK_ROLE_HUNTER":      2,
		"PACK_ROLE_SCOUT":       3,
		"PACK_ROLE_SENTRY":      4,
		"PACK_ROLE_ELDER":       5,
		"PACK_ROLE_PUP":         6,
	}
)

func (x PackRole) Enum() *PackRole {
	p := new(PackRole)
	*p = x
	return p
}

func (x PackRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackRole) Descriptor() protoreflect.EnumDescriptor {
	return file_api_howl_v1_howl_proto_enumTypes[0].Descriptor()
}

func (PackRole) Type() protoreflect.EnumType {
	return &file_api_howl_v1_howl_proto_enumTypes[0]
}

func (x PackRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackRole.Descriptor instead.
func (PackRole) EnumDescriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{0}
}

type MemberStatus int32

const (
	MemberStatus_MEMBER_STATUS_UNSPECIFIED MemberStatus = 0
	MemberStatus_MEMBER_STATUS_IDLE        MemberStatus = 1
	MemberStatus_MEMBER_STATUS_HUNTING     MemberStatus = 2
	MemberStatus_MEMBER_STATUS_TRACKING    MemberStatus = 3
	MemberStatus_MEMBER_STATUS_RESTING     MemberStatus = 4
	MemberStatus_MEMBER_STATUS_FAILED      MemberStatus = 5
)

// Enum value maps for MemberStatus.
var (
	MemberStatus_name = map[int32]string{
		0: "MEMBER_STATUS_UNSPECIFIED",
		1: "MEMBER_STATUS_IDLE",
		2: "MEMBER_STATUS_HUNTING",
		3: "MEMBER_STATUS_TRACKING",
		4: "MEMBER_STATUS_RESTING",
		5: "MEMBER_STATUS_FAILED",
	}
	MemberStatus_value = map[string]int32{
		"MEMBER_STATUS_UNSPECIFIED": 0,
		"MEMBER_STATUS_IDLE":        1,
		"MEMBER_STATUS_HUNTING":     2,
		"MEMBER_STATUS_TRACKING":    3,
		"MEMBER_STATUS_RESTING":     4,
		"MEMBER_STATUS_FAILED":      5,
	}
)

func (x MemberStatus) Enum() *MemberStatus {
	p := new(MemberStatus)
	*p = x
	return p
}

func (x MemberStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_howl_v1_howl_proto_enumTypes[1].Descriptor()
}

func (MemberStatus) Type() protoreflect.EnumType {
	return &file_api_howl_v1_howl_proto_enumTypes[1]
}

func (x MemberStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberStatus.Descriptor instead.
func (MemberStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{1}
}

type HowlType int32

const (
	HowlType_HOWL_TYPE_UNSPECIFIED HowlType = 0
	HowlType_HOWL_TYPE_ALERT       HowlType = 1
	HowlType_HOWL_TYPE_GATHER      HowlType = 2
	HowlType_HOWL_TYPE_RETREAT     HowlType = 3
	HowlType_HOWL_TYPE_SUCCESS     HowlType = 4
	HowlType_HOWL_TYPE_FAILURE     HowlType = 5
)

// Enum value maps for HowlType.
var (
	HowlType_name = map[int32]string{
		0: "HOWL_TYPE_UNSPECIFIED",
		1: "HOWL_TYPE_ALERT",
		2: "HOWL_TYPE_GATHER",
		3: "HOWL_TYPE_RETREAT",
		4: "HOWL_TYPE_SUCCESS",
		5: "HOWL_TYPE_FAILURE",
	}
	HowlType_value = map[string]int32{
		"HOWL_TYPE_UNSPECIFIED": 0,
		"HOWL_TYPE_ALERT":       1,
		"HOWL_TYPE_GATHER":      2,
		"HOWL_TYPE_RETREAT":     3,
		"HOWL_TYPE_SUCCESS":     4,
		"HOWL_TYPE_FAILURE":     5,
	}
)

func (x HowlType) Enum() *HowlType {
	p := new(HowlType)
	*p = x
	return p
}

func (x HowlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HowlType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_howl_v1_howl_proto_enumTypes[2].Descriptor()
}

func (HowlType) Type() protoreflect.EnumType {
	return &file_api_howl_v1_howl_proto_enumTypes[2]
}

func (x HowlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HowlType.Descriptor instead.
func (HowlType) EnumDescriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{2}
}

type FlowControl int32

const (
	FlowControl_FLOW_CONTROL_UNSPECIFIED    FlowControl = 0
	FlowControl_FLOW_CONTROL_ALLOW_ALL      FlowControl = 1
	FlowControl_FLOW_CONTROL_WARN_ONLY      FlowControl = 2
	FlowControl_FLOW_CONTROL_STRICT         FlowControl = 3
	FlowControl_FLOW_CONTROL_WHITELIST_ONLY FlowControl = 4
	FlowControl_FLOW_CONTROL_AIRGAP_MODE    FlowControl = 5
)

// Enum value maps for FlowControl.
var (
	FlowControl_name = map[int32]string{
		0: "FLOW_CONTROL_UNSPECIFIED",
		1: "FLOW_CONTROL_ALLOW_ALL",
		2: "FLOW_CONTROL_WARN_ONLY",
		3: "FLOW_CONTROL_STRICT",
		4: "FLOW_CONTROL_WHITELIST_ONLY",
		5: "FLOW_CONTROL_AIRGAP_MODE",
	}
	FlowControl_value = map[string]int32{
		"FLOW_CONTROL_UNSPECIFIED":    0,
		"FLOW_CONTROL_ALLOW_ALL":      1,
		"FLOW_CONTROL_WARN_ONLY":      2,
		"FLOW_CONTROL_STRICT":         3,
		"FLOW_CONTROL_WHITELIST_ONLY": 4,
		"FLOW_CONTROL_AIRGAP_MODE":    5,
	}
)

func (x FlowControl) Enum() *FlowControl {
	p := new(FlowControl)
	*p = x
	return p
}

func (x FlowControl) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlowControl) Descriptor() protoreflect.EnumDescriptor {
	return file_api_howl_v1_howl_proto_enumTypes[3].Descriptor()
}

func (FlowControl) Type() protoreflect.EnumType {
	return &file_api_howl_v1_howl_proto_enumTypes[3]
}

func (x FlowControl) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlowControl.Descriptor instead.
func (FlowControl) EnumDescriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{3}
}

type AuditLevel int32

const (
	AuditLevel_AUDIT_LEVEL_UNSPECIFIED AuditLevel = 0
	AuditLevel_AUDIT_LEVEL_NONE        AuditLevel = 1
	AuditLevel_AUDIT_LEVEL_MINIMAL     AuditLevel = 2
	AuditLevel_AUDIT_LEVEL_NORMAL      AuditLevel = 3
	AuditLevel_AUDIT_LEVEL_VERBOSE     AuditLevel = 4
	AuditLevel_AUDIT_LEVEL_COMPLIANCE  AuditLevel = 5
	AuditLevel_AUDIT_LEVEL_FORENSIC    AuditLevel = 6
)

// Enum value maps for AuditLevel.
var (
	AuditLevel_name = map[int32]string{
		0: "AUDIT_LEVEL_UNSPECIFIED",
		1: "AUDIT_LEVEL_NONE",
		2: "AUDIT_LEVEL_MINIMAL",
		3: "AUDIT_LEVEL_NORMAL",
		4: "AUDIT_LEVEL_VERBOSE",
		5: "AUDIT_LEVEL_COMPLIANCE",
		6: "AUDIT_LEVEL_FORENSIC",
	}
	AuditLevel_value = map[string]int32{
		"AUDIT_LEVEL_UNSPECIFIED": 0,
		"AUDIT_LEVEL_NONE":        1,
		"AUDIT_LEVEL_MINIMAL":     2,
		"AUDIT_LEVEL_NORMAL":      3,
		"AUDIT_LEVEL_VERBOSE":     4,
		"AUDIT_LEVEL_COMPLIANCE":  5,
		"AUDIT_LEVEL_FORENSIC":    6,
	}
)

func (x AuditLevel) Enum() *AuditLevel {
	p := new(AuditLevel)
	*p = x
	return p
}

func (x AuditLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_api_howl_v1_howl_proto_enumTypes[4].Descriptor()
}

func (AuditLevel) Type() protoreflect.EnumType {
	return &file_api_howl_v1_howl_proto_enumTypes[4]
}

func (x AuditLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditLevel.Descriptor instead.
func (AuditLevel) EnumDescriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{4}
}

// PackMember represents an agent in the pack
type PackMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          PackRole               `protobuf:"varint,2,opt,name=role,proto3,enum=howl.v1.PackRole" json:"role,omitempty"`
	Provider      string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        MemberStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=howl.v1.MemberStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackMember) Reset() {
	*x = PackMember{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackMember) ProtoMessage() {}

func (x *PackMember) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackMember.ProtoReflect.Descriptor instead.
func (*PackMember) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{0}
}

func (x *PackMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PackMember) GetRole() PackRole {
	if x != nil {
		return x.Role
	}
	return PackRole_PACK_ROLE_UNSPECIFIED
}

func (x *PackMember) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *PackMember) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *PackMember) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *PackMember) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MEMBER_STATUS_UNSPECIFIED
}

// SummonRequest initiates an AI request
type SummonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackId        string                 `protobuf:"bytes,1,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Member        *PackMember            `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	Prompt        string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Options       map[string]*anypb.Any  `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Security      *SecurityProfile       `protobuf:"bytes,6,opt,name=security,proto3" json:"security,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummonRequest) Reset() {
	*x = SummonRequest{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummonRequest) ProtoMessage() {}

func (x *SummonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummonRequest.ProtoReflect.Descriptor instead.
func (*SummonRequest) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{1}
}

func (x *SummonRequest) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

func (x *SummonRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SummonRequest) GetMember() *PackMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *SummonRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SummonRequest) GetOptions() map[string]*anypb.Any {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *SummonRequest) GetSecurity() *SecurityProfile {
	if x != nil {
		return x.Security
	}
	return nil
}

func (x *SummonRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// SummonResponse returns the initial response
type SummonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	HuntId        string                 `protobuf:"bytes,2,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	Status        MemberStatus           `protobuf:"varint,3,opt,name=status,proto3,enum=howl.v1.MemberStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummonResponse) Reset() {
	*x = SummonResponse{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummonResponse) ProtoMessage() {}

func (x *SummonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummonResponse.ProtoReflect.Descriptor instead.
func (*SummonResponse) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{2}
}

func (x *SummonResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SummonResponse) GetHuntId() string {
	if x != nil {
		return x.HuntId
	}
	return ""
}

func (x *SummonResponse) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MEMBER_STATUS_UNSPECIFIED
}

func (x *SummonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SummonResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// TrackRequest monitors a hunt
type TrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackId        string                 `protobuf:"bytes,1,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
	HuntId        string                 `protobuf:"bytes,2,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackRequest) Reset() {
	*x = TrackRequest{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackRequest) ProtoMessage() {}

func (x *TrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackRequest.ProtoReflect.Descriptor instead.
func (*TrackRequest) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{3}
}

func (x *TrackRequest) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

func (x *TrackRequest) GetHuntId() string {
	if x != nil {
		return x.HuntId
	}
	return ""
}

// TrackResponse provides hunt updates
type TrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HuntId        string                 `protobuf:"bytes,1,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	Status        MemberStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=howl.v1.MemberStatus" json:"status,omitempty"`
	Progress      float32                `protobuf:"fixed32,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Usage         *TokenUsage            `protobuf:"bytes,5,opt,name=usage,proto3" json:"usage,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackResponse) Reset() {
	*x = TrackResponse{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackResponse) ProtoMessage() {}

func (x *TrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackResponse.ProtoReflect.Descriptor instead.
func (*TrackResponse) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{4}
}

func (x *TrackResponse) GetHuntId() string {
	if x != nil {
		return x.HuntId
	}
	return ""
}

func (x *TrackResponse) GetStatus() MemberStatus {
	if x != nil {
		return x.Status
	}
	return MemberStatus_MEMBER_STATUS_UNSPECIFIED
}

func (x *TrackResponse) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *TrackResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TrackResponse) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *TrackResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// CircleRequest for multi-agent collaboration
type CircleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackId        string                 `protobuf:"bytes,1,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
	CircleId      string                 `protobuf:"bytes,2,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	Members       []*PackMember          `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	Objective     string                 `protobuf:"bytes,4,opt,name=objective,proto3" json:"objective,omitempty"`
	Context       map[string]*anypb.Any  `protobuf:"bytes,5,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircleRequest) Reset() {
	*x = CircleRequest{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircleRequest) ProtoMessage() {}

func (x *CircleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircleRequest.ProtoReflect.Descriptor instead.
func (*CircleRequest) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{5}
}

func (x *CircleRequest) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

func (x *CircleRequest) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *CircleRequest) GetMembers() []*PackMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *CircleRequest) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

func (x *CircleRequest) GetContext() map[string]*anypb.Any {
	if x != nil {
		return x.Context
	}
	return nil
}

// CircleResponse from collaborating agents
type CircleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CircleId      string                 `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Artifacts     map[string]*anypb.Any  `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircleResponse) Reset() {
	*x = CircleResponse{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircleResponse) ProtoMessage() {}

func (x *CircleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircleResponse.ProtoReflect.Descriptor instead.
func (*CircleResponse) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{6}
}

func (x *CircleResponse) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *CircleResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CircleResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CircleResponse) GetArtifacts() map[string]*anypb.Any {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *CircleResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HowlRequest broadcasts to pack
type HowlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PackId        string                 `protobuf:"bytes,1,opt,name=pack_id,json=packId,proto3" json:"pack_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Type          HowlType               `protobuf:"varint,3,opt,name=type,proto3,enum=howl.v1.HowlType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HowlRequest) Reset() {
	*x = HowlRequest{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HowlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HowlRequest) ProtoMessage() {}

func (x *HowlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HowlRequest.ProtoReflect.Descriptor instead.
func (*HowlRequest) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{7}
}

func (x *HowlRequest) GetPackId() string {
	if x != nil {
		return x.PackId
	}
	return ""
}

func (x *HowlRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *HowlRequest) GetType() HowlType {
	if x != nil {
		return x.Type
	}
	return HowlType_HOWL_TYPE_UNSPECIFIED
}

func (x *HowlRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HowlRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// HowlResponse acknowledges broadcast
type HowlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HowlId        string                 `protobuf:"bytes,1,opt,name=howl_id,json=howlId,proto3" json:"howl_id,omitempty"`
	Receivers     int32                  `protobuf:"varint,2,opt,name=receivers,proto3" json:"receivers,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HowlResponse) Reset() {
	*x = HowlResponse{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HowlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HowlResponse) ProtoMessage() {}

func (x *HowlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HowlResponse.ProtoReflect.Descriptor instead.
func (*HowlResponse) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{8}
}

func (x *HowlResponse) GetHowlId() string {
	if x != nil {
		return x.HowlId
	}
	return ""
}

func (x *HowlResponse) GetReceivers() int32 {
	if x != nil {
		return x.Receivers
	}
	return 0
}

func (x *HowlResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// SecurityProfile defines security constraints
type SecurityProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FlowControl      FlowControl            `protobuf:"varint,2,opt,name=flow_control,json=flowControl,proto3,enum=howl.v1.FlowControl" json:"flow_control,omitempty"`
	AuditLevel       AuditLevel             `protobuf:"varint,3,opt,name=audit_level,json=auditLevel,proto3,enum=howl.v1.AuditLevel" json:"audit_level,omitempty"`
	MfaRequired      bool                   `protobuf:"varint,4,opt,name=mfa_required,json=mfaRequired,proto3" json:"mfa_required,omitempty"`
	EncryptAtRest    bool                   `protobuf:"varint,5,opt,name=encrypt_at_rest,json=encryptAtRest,proto3" json:"encrypt_at_rest,omitempty"`
	AllowedProviders []string               `protobuf:"bytes,6,rep,name=allowed_providers,json=allowedProviders,proto3" json:"allowed_providers,omitempty"`
	CustomPolicies   map[string]string      `protobuf:"bytes,7,rep,name=custom_policies,json=customPolicies,proto3" json:"custom_policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SecurityProfile) Reset() {
	*x = SecurityProfile{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityProfile) ProtoMessage() {}

func (x *SecurityProfile) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityProfile.ProtoReflect.Descriptor instead.
func (*SecurityProfile) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{9}
}

func (x *SecurityProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityProfile) GetFlowControl() FlowControl {
	if x != nil {
		return x.FlowControl
	}
	return FlowControl_FLOW_CONTROL_UNSPECIFIED
}

func (x *SecurityProfile) GetAuditLevel() AuditLevel {
	if x != nil {
		return x.AuditLevel
	}
	return AuditLevel_AUDIT_LEVEL_UNSPECIFIED
}

func (x *SecurityProfile) GetMfaRequired() bool {
	if x != nil {
		return x.MfaRequired
	}
	return false
}

func (x *SecurityProfile) GetEncryptAtRest() bool {
	if x != nil {
		return x.EncryptAtRest
	}
	return false
}

func (x *SecurityProfile) GetAllowedProviders() []string {
	if x != nil {
		return x.AllowedProviders
	}
	return nil
}

func (x *SecurityProfile) GetCustomPolicies() map[string]string {
	if x != nil {
		return x.CustomPolicies
	}
	return nil
}

// TokenUsage tracks resource consumption
type TokenUsage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	EstimatedCost    float64                `protobuf:"fixed64,4,opt,name=estimated_cost,json=estimatedCost,proto3" json:"estimated_cost,omitempty"`
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_api_howl_v1_howl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_api_howl_v1_howl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_api_howl_v1_howl_proto_rawDescGZIP(), []int{10}
}

func (x *TokenUsage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *TokenUsage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *TokenUsage) GetEstimatedCost() float64 {
	if x != nil {
		return x.EstimatedCost
	}
	return 0
}

func (x *TokenUsage) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_api_howl_v1_howl_proto protoreflect.FileDescriptor

const file_api_howl_v1_howl_proto_rawDesc = "" +
	"\n" +
	"\x16api/howl/v1/howl.proto\x12\ahowl.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xb0\x02\n" +
	"\n" +
	"PackMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x04role\x18\x02 \x01(\x0e2\x11.howl.v1.PackRoleR\x04role\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12I\n" +
	"\fcapabilities\x18\x05 \x03(\v2%.howl.v1.PackMember.CapabilitiesEntryR\fcapabilities\x12-\n" +
	"\x06status\x18\x06 \x01(\x0e2\x15.howl.v1.MemberStatusR\x06status\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x03\n" +
	"\rSummonRequest\x12\x17\n" +
	"\apack_id\x18\x01 \x01(\tR\x06packId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12+\n" +
	"\x06member\x18\x03 \x01(\v2\x13.howl.v1.PackMemberR\x06member\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12=\n" +
	"\aoptions\x18\x05 \x03(\v2#.howl.v1.SummonRequest.OptionsEntryR\aoptions\x124\n" +
	"\bsecurity\x18\x06 \x01(\v2\x18.howl.v1.SecurityProfileR\bsecurity\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1aP\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x0eSummonResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\ahunt_id\x18\x02 \x01(\tR\x06huntId\x12-\n" +
	"\x06status\x18\x03 \x01(\x0e2\x15.howl.v1.MemberStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"@\n" +
	"\fTrackRequest\x12\x17\n" +
	"\apack_id\x18\x01 \x01(\tR\x06packId\x12\x17\n" +
	"\ahunt_id\x18\x02 \x01(\tR\x06huntId\"\xf2\x01\n" +
	"\rTrackResponse\x12\x17\n" +
	"\ahunt_id\x18\x01 \x01(\tR\x06huntId\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.howl.v1.MemberStatusR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x02R\bprogress\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12)\n" +
	"\x05usage\x18\x05 \x01(\v2\x13.howl.v1.TokenUsageR\x05usage\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa3\x02\n" +
	"\rCircleRequest\x12\x17\n" +
	"\apack_id\x18\x01 \x01(\tR\x06packId\x12\x1b\n" +
	"\tcircle_id\x18\x02 \x01(\tR\bcircleId\x12-\n" +
	"\amembers\x18\x03 \x03(\v2\x13.howl.v1.PackMemberR\amembers\x12\x1c\n" +
	"\tobjective\x18\x04 \x01(\tR\tobjective\x12=\n" +
	"\acontext\x18\x05 \x03(\v2#.howl.v1.CircleRequest.ContextEntryR\acontext\x1aP\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\xb8\x02\n" +
	"\x0eCircleResponse\x12\x1b\n" +
	"\tcircle_id\x18\x01 \x01(\tR\bcircleId\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12D\n" +
	"\tartifacts\x18\x04 \x03(\v2&.howl.v1.CircleResponse.ArtifactsEntryR\tartifacts\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1aR\n" +
	"\x0eArtifactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value:\x028\x01\"\x81\x02\n" +
	"\vHowlRequest\x12\x17\n" +
	"\apack_id\x18\x01 \x01(\tR\x06packId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.howl.v1.HowlTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12>\n" +
	"\bmetadata\x18\x05 \x03(\v2\".howl.v1.HowlRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x7f\n" +
	"\fHowlResponse\x12\x17\n" +
	"\ahowl_id\x18\x01 \x01(\tR\x06howlId\x12\x1c\n" +
	"\treceivers\x18\x02 \x01(\x05R\treceivers\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xa6\x03\n" +
	"\x0fSecurityProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\fflow_control\x18\x02 \x01(\x0e2\x14.howl.v1.FlowControlR\vflowControl\x124\n" +
	"\vaudit_level\x18\x03 \x01(\x0e2\x13.howl.v1.AuditLevelR\n" +
	"auditLevel\x12!\n" +
	"\fmfa_required\x18\x04 \x01(\bR\vmfaRequired\x12&\n" +
	"\x0fencrypt_at_rest\x18\x05 \x01(\bR\rencryptAtRest\x12+\n" +
	"\x11allowed_providers\x18\x06 \x03(\tR\x10allowedProviders\x12U\n" +
	"\x0fcustom_policies\x18\a \x03(\v2,.howl.v1.SecurityProfile.CustomPoliciesEntryR\x0ecustomPolicies\x1aA\n" +
	"\x13CustomPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x01\n" +
	"\n" +
	"TokenUsage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\x12%\n" +
	"\x0eestimated_cost\x18\x04 \x01(\x01R\restimatedCost\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency*\xa3\x01\n" +
	"\bPackRole\x12\x19\n" +
	"\x15PACK_ROLE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPACK_ROLE_ALPHA\x10\x01\x12\x14\n" +
	"\x10PACK_ROLE_HUNTER\x10\x02\x12\x13\n" +
	"\x0fPACK_ROLE_SCOUT\x10\x03\x12\x14\n" +
	"\x10PACK_ROLE_SENTRY\x10\x04\x12\x13\n" +
	"\x0fPACK_ROLE_ELDER\x10\x05\x12\x11\n" +
	"\rPACK_ROLE_PUP\x10\x06*\xb1\x01\n" +
	"\fMemberStatus\x12\x1d\n" +
	"\x19MEMBER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12MEMBER_STATUS_IDLE\x10\x01\x12\x19\n" +
	"\x15MEMBER_STATUS_HUNTING\x10\x02\x12\x1a\n" +
	"\x16MEMBER_STATUS_TRACKING\x10\x03\x12\x19\n" +
	"\x15MEMBER_STATUS_RESTING\x10\x04\x12\x18\n" +
	"\x14MEMBER_STATUS_FAILED\x10\x05*\x95\x01\n" +
	"\bHowlType\x12\x19\n" +
	"\x15HOWL_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHOWL_TYPE_ALERT\x10\x01\x12\x14\n" +
	"\x10HOWL_TYPE_GATHER\x10\x02\x12\x15\n" +
	"\x11HOWL_TYPE_RETREAT\x10\x03\x12\x15\n" +
	"\x11HOWL_TYPE_SUCCESS\x10\x04\x12\x15\n" +
	"\x11HOWL_TYPE_FAILURE\x10\x05*\xbb\x01\n" +
	"\vFlowControl\x12\x1c\n" +
	"\x18FLOW_CONTROL_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16FLOW_CONTROL_ALLOW_ALL\x10\x01\x12\x1a\n" +
	"\x16FLOW_CONTROL_WARN_ONLY\x10\x02\x12\x17\n" +
	"\x13FLOW_CONTROL_STRICT\x10\x03\x12\x1f\n" +
	"\x1bFLOW_CONTROL_WHITELIST_ONLY\x10\x04\x12\x1c\n" +
	"\x18FLOW_CONTROL_AIRGAP_MODE\x10\x05*\xbf\x01\n" +
	"\n" +
	"AuditLevel\x12\x1b\n" +
	"\x17AUDIT_LEVEL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AUDIT_LEVEL_NONE\x10\x01\x12\x17\n" +
	"\x13AUDIT_LEVEL_MINIMAL\x10\x02\x12\x16\n" +
	"\x12AUDIT_LEVEL_NORMAL\x10\x03\x12\x17\n" +
	"\x13AUDIT_LEVEL_VERBOSE\x10\x04\x12\x1a\n" +
	"\x16AUDIT_LEVEL_COMPLIANCE\x10\x05\x12\x18\n" +
	"\x14AUDIT_LEVEL_FORENSIC\x10\x062\xf6\x01\n" +
	"\vPackService\x129\n" +
	"\x06Summon\x12\x16.howl.v1.SummonRequest\x1a\x17.howl.v1.SummonResponse\x128\n" +
	"\x05Track\x12\x15.howl.v1.TrackRequest\x1a\x16.howl.v1.TrackResponse0\x01\x12=\n" +
	"\x06Circle\x12\x16.howl.v1.CircleRequest\x1a\x17.howl.v1.CircleResponse(\x010\x01\x123\n" +
	"\x04Howl\x12\x14.howl.v1.HowlRequest\x1a\x15.howl.v1.HowlResponseB1Z/github.com/macawi-ai/canidae/api/howl/v1;howlv1b\x06proto3"

var (
	file_api_howl_v1_howl_proto_rawDescOnce sync.Once
	file_api_howl_v1_howl_proto_rawDescData []byte
)

func file_api_howl_v1_howl_proto_rawDescGZIP() []byte {
	file_api_howl_v1_howl_proto_rawDescOnce.Do(func() {
		file_api_howl_v1_howl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_howl_v1_howl_proto_rawDesc), len(file_api_howl_v1_howl_proto_rawDesc)))
	})
	return file_api_howl_v1_howl_proto_rawDescData
}

var file_api_howl_v1_howl_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_howl_v1_howl_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_howl_v1_howl_proto_goTypes = []any{
	(PackRole)(0),                 // 0: howl.v1.PackRole
	(MemberStatus)(0),             // 1: howl.v1.MemberStatus
	(HowlType)(0),                 // 2: howl.v1.HowlType
	(FlowControl)(0),              // 3: howl.v1.FlowControl
	(AuditLevel)(0),               // 4: howl.v1.AuditLevel
	(*PackMember)(nil),            // 5: howl.v1.PackMember
	(*SummonRequest)(nil),         // 6: howl.v1.SummonRequest
	(*SummonResponse)(nil),        // 7: howl.v1.SummonResponse
	(*TrackRequest)(nil),          // 8: howl.v1.TrackRequest
	(*TrackResponse)(nil),         // 9: howl.v1.TrackResponse
	(*CircleRequest)(nil),         // 10: howl.v1.CircleRequest
	(*CircleResponse)(nil),        // 11: howl.v1.CircleResponse
	(*HowlRequest)(nil),           // 12: howl.v1.HowlRequest
	(*HowlResponse)(nil),          // 13: howl.v1.HowlResponse
	(*SecurityProfile)(nil),       // 14: howl.v1.SecurityProfile
	(*TokenUsage)(nil),            // 15: howl.v1.TokenUsage
	nil,                           // 16: howl.v1.PackMember.CapabilitiesEntry
	nil,                           // 17: howl.v1.SummonRequest.OptionsEntry
	nil,                           // 18: howl.v1.CircleRequest.ContextEntry
	nil,                           // 19: howl.v1.CircleResponse.ArtifactsEntry
	nil,                           // 20: howl.v1.HowlRequest.MetadataEntry
	nil,                           // 21: howl.v1.SecurityProfile.CustomPoliciesEntry
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 23: google.protobuf.Any
}
var file_api_howl_v1_howl_proto_depIdxs = []int32{
	0,  // 0: howl.v1.PackMember.role:type_name -> howl.v1.PackRole
	16, // 1: howl.v1.PackMember.capabilities:type_name -> howl.v1.PackMember.CapabilitiesEntry
	1,  // 2: howl.v1.PackMember.status:type_name -> howl.v1.MemberStatus
	5,  // 3: howl.v1.SummonRequest.member:type_name -> howl.v1.PackMember
	17, // 4: howl.v1.SummonRequest.options:type_name -> howl.v1.SummonRequest.OptionsEntry
	14, // 5: howl.v1.SummonRequest.security:type_name -> howl.v1.SecurityProfile
	22, // 6: howl.v1.SummonRequest.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 7: howl.v1.SummonResponse.status:type_name -> howl.v1.MemberStatus
	22, // 8: howl.v1.SummonResponse.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 9: howl.v1.TrackResponse.status:type_name -> howl.v1.MemberStatus
	15, // 10: howl.v1.TrackResponse.usage:type_name -> howl.v1.TokenUsage
	22, // 11: howl.v1.TrackResponse.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 12: howl.v1.CircleRequest.members:type_name -> howl.v1.PackMember
	18, // 13: howl.v1.CircleRequest.context:type_name -> howl.v1.CircleRequest.ContextEntry
	19, // 14: howl.v1.CircleResponse.artifacts:type_name -> howl.v1.CircleResponse.ArtifactsEntry
	22, // 15: howl.v1.CircleResponse.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 16: howl.v1.HowlRequest.type:type_name -> howl.v1.HowlType
	20, // 17: howl.v1.HowlRequest.metadata:type_name -> howl.v1.HowlRequest.MetadataEntry
	22, // 18: howl.v1.HowlResponse.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 19: howl.v1.SecurityProfile.flow_control:type_name -> howl.v1.FlowControl
	4,  // 20: howl.v1.SecurityProfile.audit_level:type_name -> howl.v1.AuditLevel
	21, // 21: howl.v1.SecurityProfile.custom_policies:type_name -> howl.v1.SecurityProfile.CustomPoliciesEntry
	23, // 22: howl.v1.SummonRequest.OptionsEntry.value:type_name -> google.protobuf.Any
	23, // 23: howl.v1.CircleRequest.ContextEntry.value:type_name -> google.protobuf.Any
	23, // 24: howl.v1.CircleResponse.ArtifactsEntry.value:type_name -> google.protobuf.Any
	6,  // 25: howl.v1.PackService.Summon:input_type -> howl.v1.SummonRequest
	8,  // 26: howl.v1.PackService.Track:input_type -> howl.v1.TrackRequest
	10, // 27: howl.v1.PackService.Circle:input_type -> howl.v1.CircleRequest
	12, // 28: howl.v1.PackService.Howl:input_type -> howl.v1.HowlRequest
	7,  // 29: howl.v1.PackService.Summon:output_type -> howl.v1.SummonResponse
	9,  // 30: howl.v1.PackService.Track:output_type -> howl.v1.TrackResponse
	11, // 31: howl.v1.PackService.Circle:output_type -> howl.v1.CircleResponse
	13, // 32: howl.v1.PackService.Howl:output_type -> howl.v1.HowlResponse
	29, // [29:33] is the sub-list for method output_type
	25, // [25:29] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_howl_v1_howl_proto_init() }
func file_api_howl_v1_howl_proto_init() {
	if File_api_howl_v1_howl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_howl_v1_howl_proto_rawDesc), len(file_api_howl_v1_howl_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_howl_v1_howl_proto_goTypes,
		DependencyIndexes: file_api_howl_v1_howl_proto_depIdxs,
		EnumInfos:         file_api_howl_v1_howl_proto_enumTypes,
		MessageInfos:      file_api_howl_v1_howl_proto_msgTypes,
	}.Build()
	File_api_howl_v1_howl_proto = out.File
	file_api_howl_v1_howl_proto_goTypes = nil
	file_api_howl_v1_howl_proto_depIdxs = nil
}
