#!/bin/bash
# Setup script for Synth administrative access on canidae server
# Based on Sister Gemini's security recommendations

set -euo pipefail

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}🦊 Setting up Synth's administrative access${NC}"
echo "============================================="

# Create a sudoers file for CANIDAE deployment tasks
cat << 'EOF' > /tmp/canidae-sudoers
# CANIDAE deployment permissions for cy user
# Generated by Synth for pack operations

# User management for rootless Podman
cy ALL=(ALL:ALL) NOPASSWD: /usr/sbin/useradd -r -m -s /bin/bash canidae
cy ALL=(ALL:ALL) NOPASSWD: /usr/sbin/loginctl enable-linger canidae
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/tee -a /etc/subuid
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/tee -a /etc/subgid

# Directory operations for /opt/canidae
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/mkdir -p /opt/canidae/*
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/chown -R canidae\:canidae /opt/canidae
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/chown -R canidae\:canidae /opt/canidae/*
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/chmod * /opt/canidae/*

# Podman operations as canidae user
cy ALL=(canidae) NOPASSWD: /usr/bin/podman *

# Systemd operations for services
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/systemctl --user -M canidae@ *
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/systemctl daemon-reload

# Check existing users and groups
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/id canidae
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/grep ^canidae\: /etc/subuid
cy ALL=(ALL:ALL) NOPASSWD: /usr/bin/grep ^canidae\: /etc/subgid
EOF

echo -e "${YELLOW}This script will add the following sudoers rules:${NC}"
echo ""
cat /tmp/canidae-sudoers
echo ""
echo -e "${YELLOW}Please review these rules carefully!${NC}"
echo ""
echo "To install on the canidae server:"
echo -e "${GREEN}1. SSH to the server: ssh cy@192.168.1.38${NC}"
echo -e "${GREEN}2. Copy this file: scp cy@$(hostname -I | awk '{print $1}'):/tmp/canidae-sudoers /tmp/${NC}"
echo -e "${GREEN}3. Install it: sudo cp /tmp/canidae-sudoers /etc/sudoers.d/50-canidae${NC}"
echo -e "${GREEN}4. Verify: sudo visudo -c${NC}"
echo ""
echo "These permissions allow:"
echo "  • Creating the canidae user for rootless Podman"
echo "  • Managing /opt/canidae directory structure"
echo "  • Running Podman commands as the canidae user"
echo "  • Managing systemd services"
echo ""
echo -e "${BLUE}All operations are limited to CANIDAE-specific paths and commands${NC}"