apiVersion: v1
kind: Pod
metadata:
  name: canidae-dev
  labels:
    environment: dev
    project: canidae
    pack: alpha
spec:
  hostname: canidae-dev
  containers:
  
  # NATS Message Bus
  - name: nats
    image: docker.io/library/nats:latest
    ports:
    - containerPort: 4222  # Client connections
      hostPort: 14222
    - containerPort: 8222  # HTTP monitoring
      hostPort: 18222
    - containerPort: 6222  # Cluster
    command: ["nats-server"]
    args:
    - "--jetstream"
    - "--store_dir=/data"
    - "--cluster_name=CANIDAE"
    - "--http_port=8222"
    - "--name=nats-dev"
    volumeMounts:
    - mountPath: /data
      name: nats-data
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  
  # CANIDAE Ring Orchestrator
  - name: ring
    image: localhost/canidae-ring:dev
    ports:
    - containerPort: 8080  # API
      hostPort: 18080
    - containerPort: 9090  # Metrics
      hostPort: 19090
    env:
    - name: CANIDAE_ENV
      value: "development"
    - name: NATS_URL
      value: "nats://localhost:4222"
    - name: FLOW_CONTROL_MODE
      value: "permissive"
    - name: CHAOS_ENABLED
      value: "true"
    - name: LOG_LEVEL
      value: "debug"
    volumeMounts:
    - mountPath: /config
      name: config
    - mountPath: /logs
      name: logs
    resources:
      limits:
        memory: "1Gi"
        cpu: "1000m"
      requests:
        memory: "512Mi"
        cpu: "500m"
  
  # Provider Gateway (handles all AI providers)
  - name: provider-gateway
    image: localhost/canidae-providers:dev
    ports:
    - containerPort: 3000  # Provider API
      hostPort: 13000
    env:
    - name: CANIDAE_ENV
      value: "development"
    - name: NATS_URL
      value: "nats://localhost:4222"
    - name: PROVIDERS_ENABLED
      value: "mock,anthropic,openai"
    - name: RATE_LIMIT_MODE
      value: "relaxed"
    volumeMounts:
    - mountPath: /secrets
      name: secrets
      readOnly: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
  
  volumes:
  # Persistent storage for NATS JetStream
  - name: nats-data
    hostPath:
      path: /opt/canidae/dev/nats-data
      type: DirectoryOrCreate
  
  # Configuration files
  - name: config
    hostPath:
      path: /opt/canidae/dev/config
      type: DirectoryOrCreate
  
  # Logs
  - name: logs
    hostPath:
      path: /opt/canidae/dev/logs
      type: DirectoryOrCreate
  
  # Secrets (API keys, etc.)
  - name: secrets
    hostPath:
      path: /opt/canidae/secrets
      type: Directory
  
  restartPolicy: Always
  
  # Security context for rootless operation
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault